# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='foto',
            field=models.ImageField(default='fotos/organic.png', upload_to='media/fotos'),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='url',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='correoElectronico',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/videos'),
        ),
    ]
