# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0002_auto_20160903_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concurso',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concurso',
            name='foto',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
